import smtplib
import json
import os
import markdown
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

class EmailSubscriber:
    def __init__(self, storage_file="subscribers.json"):
        self.storage_file = storage_file
        self.load_subscribers()
    
    def load_subscribers(self):
        try:
            with open(self.storage_file, 'r') as f:
                self.subscribers = json.load(f)
        except (FileNotFoundError, json.JSONDecodeError):
            self.subscribers = []
    
    def add_subscriber(self, email, name=""):
        # (Keep your existing add_subscriber logic here, it was fine)
        if email in [s['email'] for s in self.subscribers]:
            return False
        self.subscribers.append({
            "email": email,
            "name": name,
            "subscribed_at": datetime.now().isoformat(),
            "active": True
        })
        self.save_subscribers()
        return True

    def save_subscribers(self):
        with open(self.storage_file, 'w') as f:
            json.dump(self.subscribers, f, indent=2)

    def _convert_to_html(self, markdown_text):
        """
        Converts Markdown to HTML and wraps it in a professional email template.
        """
        # 1. Convert Markdown to raw HTML
        html_body = markdown.markdown(markdown_text)

        # 2. Wrap in a clean HTML5 Email Template with CSS
        # This CSS ensures it looks good on mobile and desktop
        full_html = f"""
        <html>
        <head>
            <style>
                body {{
                    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
                    line-height: 1.6;
                    color: #333333;
                    max-width: 600px;
                    margin: 0 auto;
                    padding: 20px;
                }}
                h1 {{ color: #2c3e50; border-bottom: 2px solid #eaeaea; padding-bottom: 10px; }}
                h2 {{ color: #34495e; margin-top: 30px; }}
                h3 {{ color: #7f8c8d; }}
                hr {{ border: 0; border-top: 1px solid #eeeeee; margin: 40px 0; }}
                strong {{ color: #2c3e50; }}
                ul {{ padding-left: 20px; }}
                li {{ margin-bottom: 5px; }}
                .footer {{
                    margin-top: 50px;
                    font-size: 12px;
                    color: #999999;
                    text-align: center;
                    border-top: 1px solid #eaeaea;
                    padding-top: 20px;
                }}
            </style>
        </head>
        <body>
            {html_body}
            
            <div class="footer">
                <p>Generated by AI on a MacBook Air M1 (8GB RAM) 🤖</p>
                <p>This is an automated research report.</p>
            </div>
        </body>
        </html>
        """
        return full_html

    def send_report(self, report_markdown, subject="Thai Digital Landscape Report"):
        """Send report to all active subscribers"""
        
        gmail_user = os.getenv("GMAIL_USER")
        gmail_password = os.getenv("GMAIL_APP_PASSWORD")
        
        if not gmail_user or not gmail_password:
            print("❌ ERROR: Gmail credentials not found in .env file")
            return
        
        smtp_server = "smtp.gmail.com"
        smtp_port = 587
        
        try:
            # Create the HTML version once
            report_html = self._convert_to_html(report_markdown)

            server = smtplib.SMTP(smtp_server, smtp_port)
            server.starttls()
            server.login(gmail_user, gmail_password)
            
            sent_count = 0
            for subscriber in self.subscribers:
                if not subscriber.get('active', True):
                    continue
                
                try:
                    # Create a Multipart message (Text + HTML)
                    msg = MIMEMultipart('alternative')
                    msg['Subject'] = f"{subject} - {datetime.now().strftime('%Y-%m-%d')}"
                    msg['From'] = gmail_user
                    msg['To'] = subscriber['email']
                    
                    # Attach both versions
                    # Email clients will choose the best one they can display (usually HTML)
                    part1 = MIMEText(report_markdown, 'plain') # Fallback
                    part2 = MIMEText(report_html, 'html')      # Main
                    
                    msg.attach(part1)
                    msg.attach(part2)
                    
                    server.send_message(msg)
                    sent_count += 1
                    print(f"✓ Sent to {subscriber['email']}")
                    
                except Exception as e:
                    print(f"✗ Failed to send to {subscriber['email']}: {e}")
            
            server.quit()
            print(f"\n📧 Report sent to {sent_count} subscribers")
            
        except Exception as e:
            print(f"❌ SMTP Error: {e}")
